services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=meditation_buddy
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_ROOT_USERNAME=root
    ports:
      - "27017:27017"

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://root:secret@mongodb:27017/meditation_buddy
